### ISSUE TITLE
OTP starting with 0 is not working

### ISSUE THREAD

**Issue by Ankitj13** [wstrange/GoogleAuth#103]
Hi Team, 
We are using your library and we got like once the OTP starts with "0" will not be authorized as it is neglecting 0, not taking within the OTP.
Have you guys faced this issue with anyone else. please confirm.
Regards
Ankit

**Comment by web-97** [comment]
No problem here, 000001 equals 1,
1 In the case where the Code must be 6 digits, there is only the unique value 000001
