### ISSUE TITLE
totp not validating with other library

### ISSUE THREAD

**Issue by joshua-bv** [wstrange/GoogleAuth#25]
I'm trying to ensure this lib will work with a ruby/python implemented totp library: [pyotp](https://github.com/nathforge/pyotp).  If I use their example secret value `base32secret3232` in your library - the totp won't validate. but if I uppercase the secret in both libraries, it validates.

**Comment by joshua-bv** [comment]
doing some digging in the other lib and they set the base64.b32decode of the interval to allow lowercase...i'll file an issue on that lib for security

**Comment by emcrisostomo** [comment]
Hi @joshua-bv, [Base32] as you can see uses only the `[A-Z]` character range in its dictionary, so it's inherently an uppercase representation. I believe the library should respect this and if somebody wants to allow case insensitiveness, then convert it to uppercase before feeding it to the library.

[Base32]: http://en.wikipedia.org/wiki/Base32

**Comment by joshua-bv** [comment]
In full agreement. Found something about a potential security issue on the encoding side of base32 that should only be upper. 

Thx for the reply
