### ISSUE TITLE
SecureRandom: the SUN provider is not available and the provider is not overridable

### ISSUE THREAD

**Issue by rhussel** [wstrange/GoogleAuth#26]
Caused by: com.warrenstrange.googleauth.GoogleAuthenticatorException: Could not initialise SecureRandom with the specified provider: SUN

**Comment by emcrisostomo** [comment]
Hi @rhussel,

The library currently gets a `SecureRandom` instance using the `SecureRandom#getInstance` method and specifying the `SHA1PRNG` algorithm and the `SUN` provider. So, the system you are using has no access to this implementation. What is it, out of curiosity?

However, the non-overridability of the provider and algorithm the library is using is an outstanding issue I'm aware of.

I'm renaming this issue for clarity's sake and leave it open until this one is resolved.

**Comment by emcrisostomo** [comment]
@rhussel,

You should now be able to override the random number generator algorithm and provider using the latest release (v. 0.5.0) which has already been published on the Sonatype's Central Repository. Please, check out its documentation to see how to do it.

**Comment by senthilkumar-kj** [comment]
hi @emcrisostomo, we can use SUN provider even when we run openjdk right? Any idea when this would fail? (or when SUN provider will not be available?)

**Comment by motcwang** [comment]
Hey, how did you solve the problem? Can you please share?

**Comment by emcrisostomo** [comment]
Hi @motcwang, yes the problem is solved and yes, I can share. I'm quoting myself a couple of posts ago:

> You should now be able to override the random number generator algorithm and provider using the latest release (v. 0.5.0) which has already been published on the Sonatype's Central Repository. Please, check out its documentation to see how to do it.

Did you check the documentation? Hint: Section 3.1, _Random Number Generator Algorithm and Provider_.

**Comment by itsaxay** [comment]
List secure rendom providers list using
```
Provider[] secureRandomProviders = Security.getProviders("SecureRandom.SHA1PRNG");
```

You can get name of provider (if any) using 
```
secureRandomProviders[0].getName();
```

**Comment by saggingskin** [comment]
alguna solución en 2024 gente

**Comment by Monle** [comment]
```Java
Provider[] secureRandomProviders = Security.getProviders("SecureRandom.SHA1PRNG");
String name = secureRandomProviders[0].getName();
System.setProperty("com.warrenstrange.googleauth.rng.algorithmProvider", name);
```
That works for me.
