### ISSUE TITLE
Secrets in Base32 are case-sensitive

### ISSUE THREAD

**Issue by rkfg** [wstrange/GoogleAuth#55]
Took me a while to find out what's wrong. Google prints the codes in lowercase but the library decodes them wrong because of [this issue](https://issues.apache.org/jira/browse/CODEC-234). After doing .toUpperCase() the codes match. Probably best not to confuse people and uppercase it anyway at [this line](https://github.com/wstrange/GoogleAuth/blob/master/src/main/java/com/warrenstrange/googleauth/GoogleAuthenticator.java#L335). While it could be patched on the Apache's side I think it's nice to cover this default Google behavior on the library's side.

**Comment by emcrisostomo** [comment]
Hi @rkfg, actually I distinctly remember checking out case sensitivity on RFC 4648, which states (emphasis mine):

>  The Base 32 encoding is designed to represent arbitrary sequences of
> octets in a form that needs to be case **insensitive** but that need not
> be human readable.

I wasn't aware of bug [codec-234](https://issues.apache.org/jira/browse/CODEC-234) though. A fix seems to be in the way, but I think in the meantime we can uppercase it.

**Comment by emcrisostomo** [comment]
Pushing release `1.1.2` to OSSRH

**Comment by emcrisostomo** [comment]
Pushed [1.1.2](https://github.com/wstrange/GoogleAuth/releases/tag/1.1.2)

```
<dependency>
  <groupId>com.warrenstrange</groupId>
  <artifactId>googleauth</artifactId>
  <version>1.1.2</version>
</dependency>
```
