### ISSUE TITLE
Error Android: Could not initialise SecureRandom with the specified provider: SUN.

### ISSUE THREAD

**Issue by ruste96** [wstrange/GoogleAuth#65]
Could not initialise SecureRandom with the specified provider: SUN. 
Another provider can be chosen setting the com.warrenstrange.googleauth.rng.algorithmProvider system property.

Can you help me?

Gradle:
compile 'com.warrenstrange:googleauth:1.1.5' //Google Auth

**Comment by emcrisostomo** [comment]
The provider can be overridden by setting the specified property. Unfortunately this library does not support and is not tested on Android. I'm not even sure what the proper course of action would be in Android. Intuitively, the process that uses the library would set that variable with a call to `System.setProperty()` (https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#setProperty(java.lang.String,%20java.lang.String)) _before_ using the library.

**Comment by prashantkh19** [comment]
@emcrisostomo  Could you please help with to what (key, value) the system property should be set?
