### ISSUE TITLE
Is there any way to generate more than 5 scratch codes using wstrange google auth library.

### ISSUE THREAD

**Issue by ranjanverma** [wstrange/GoogleAuth#67]
If we need more than 5 scratch codes then is there any way to customize scratch codes size in wstrange google auth library. We went through the code but this field is `private static final int SCRATCH_CODES = 5;`  and we did not find any way to configure it.

**Comment by emcrisostomo** [comment]
I will have a look at it.

**Comment by emcrisostomo** [comment]
Duplicates #66
