### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/DEPENDENCIES'

### ISSUE THREAD

**Issue by trantronghienit** [wstrange/GoogleAuth#82]
I have this problem on the version 1.1.2
gradle version: 5.1.1
errror: More than one file was found with OS independent path 'META-INF/DEPENDENCIES'.
please help me.

**Comment by itsaxay** [comment]
You can add this in `yourProject/app/build.gradle` inside `android{}`


   

    android {      
          packagingOptions {
            exclude 'META-INF/DEPENDENCIES'
            exclude 'META-INF/LICENSE'
            exclude 'META-INF/LICENSE.txt'
            exclude 'META-INF/license.txt'
            exclude 'META-INF/NOTICE'
            exclude 'META-INF/NOTICE.txt'
            exclude 'META-INF/notice.txt'
            exclude 'META-INF/ASL2.0'
          }          
    }
