### ISSUE TITLE
Library gives true even previous otp is changed in GAuth app

### ISSUE THREAD

**Issue by mahesh1996** [wstrange/GoogleAuth#92]
When I am adding old previous OTP during sing in, then after 15 seconds of new OTP also, it is allowing me old OTP.

e.g. my current OTP is 605372. Then I waited for that OTP to expire. My new OTP was 910511 and 15 seconds of new OTP was passed. If now I enter 605372 then also it's giving true. Below is the code I used.

```
GoogleAuthenticator gAuth = new GoogleAuthenticator();
return gAuth.authorize(userProfile.getGAuthKey(), Integer.parseInt(authCode));
```

**Comment by gdrugan** [comment]
You have a default window size of 3, that means any of the last 3 codes are true. You can drop the windowSize:
`GoogleAuthenticatorConfig config = new GoogleAuthenticatorConfig.GoogleAuthenticatorConfigBuilder().setWindowSize(1).build();
        GoogleAuthenticator gAuth = new GoogleAuthenticator(config);`
In this way, only the last code generated is valid.

**Comment by mahesh1996** [comment]
Thanks for the info.
I will try and let you know.
